stages:
- docker
- auto-update


build-and-push:
  # https://connect.adfab.fr/outils/gitlab-4-cicd-docker-and-registry
  stage: docker
  image: docker:18
  only:
  - schedules
  services:
  - docker:dind
  before_script:
  - apk add --update py-pip && pip install docker-compose
  script:
  - docker login -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"
  - docker-compose build
  - docker push "${CI_REGISTRY_IMAGE}"


auto-update:
  stage: auto-update
  image: registry.gitlab.com/jawira/plantuml
  only:
  - schedules
  before_script:
  # https://gitlab.com/gitlab-org/gitlab-ce/issues/18106#note_88176162
  - url_host=`git remote get-url origin | sed -e "s/https:\/\/gitlab-ci-token:.*@//g"`
  - git reset --hard
  - git clean -fd
  - git checkout $CI_COMMIT_REF_NAME
  - git pull origin $CI_COMMIT_REF_NAME
  - git remote set-url origin "https://$GIT_ACCESS_USER:$GIT_ACCESS_PASSWORD@${url_host}"
  - git config user.name $GIT_ACCESS_USER
  - git config user.email $GIT_ACCESS_EMAIL
  script:
  - php -v
